name: Deploy NestJS API (Caddy)

on:
  push:
    branches:
      - ci-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS
        run: npm run build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy backend to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -e

          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            mkdir -p $DEPLOY_PATH/current
            mkdir -p $DEPLOY_PATH/current/dist
          EOF

          rsync -avz --delete dist/ \
            $USER@$HOST:$DEPLOY_PATH/current/dist/

          rsync -avz package.json package-lock.json \
            $USER@$HOST:$DEPLOY_PATH/current/

          ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
            cd $DEPLOY_PATH/current
            npm ci --omit=dev

            pm2 start dist/main.js \
              --name horizontruth-api \
              --update-env || pm2 restart horizontruth-api

            pm2 save
          EOF
